import {useState, useEffect} from "react";

import Header from "./components/Header.js";
import Tasks from "./components/Tasks.js";
import AddTask from "./components/AddTask.js";

// import {useState} from "react";

// import ErrorBoundary from "./components/ErrorBoundary.js";

function App() {
  // const name = "Harish";
  // const x = 0;

  const [showAddTask, setshowAddTask] = useState(false);

  const [tasks, setTasks] = useState([
    // {
    //     id: 1,
    //     text: 'Doctors Appointment',
    //     day: 'Feb 5th at 2:30pm',
    //     reminder: true,
    // },
    // {
    //     id: 2,
    //     text: 'Meeting at School',
    //     day: 'Feb 6th at 1:30pm',
    //     reminder: true,
    // },
    // {
    //     id: 3,
    //     text: 'Food Shopping',
    //     day: 'Feb 5th at 2:30pm',
    //     reminder: false,
    // },
  ]);

  useEffect( () => {
    // // const fetchTasks =
    //   (async () => {
    //     const res = await fetch("http://localhost:5000/tasks");
    //     const data = await res.json();

    //     console.log(data);
    //   })();
    // // fetchTasks();

    // const fetchTasks =
    //   (async () => {
    //     const res = await fetch("http://localhost:5000/tasks");
    //     const data = await res.json();

    //     // console.log(data);
    //     return data;
    //   });

    const getTasks = async () => {
      const tasksFromServer = await fetchTasks();
      setTasks(tasksFromServer);
    };

    // fetchTasks();
    getTasks();
  }, []);

  // Fetch tasks
  const fetchTasks =
    (async () => {
      const res = await fetch("http://localhost:5000/tasks");
      const data = await res.json();

      // console.log(data);
      return data;
    });

  // Fetch task
  const fetchTask =
    (async (id) => {
      const res = await fetch(`http://localhost:5000/tasks/${id}`);
      const data = await res.json();

      // console.log(data);
      return data;
    });

  // Because I am dealing with tasks, I am creating a function in App.js
  const addTask = async (task) => {
    // console.log("Add", task);
    // const id = Math.floor(Math.random() * 10000) + 1; // Generate a random id
    // // The above line was generated by the VS Code smart editor.
    // // console.log(id);
    // const newTask = {id, ...task};
    // setTasks([...tasks, newTask]);

    const res = await fetch(
      `http://localhost:5000/tasks`,
      {
        method: "POST",
        headers: {
          "Content-type": "application/json"
        },
        body: JSON.stringify(task),
      }
    );

    const data= await res.json();

    setTasks([...tasks, data])
  };

  // Delete and/ add tasks. However we are not using add task in this example.
  const deleteTask = async (id) => {

    // Deleting from the server
    await fetch(
      `http://localhost:5000/tasks/${id}`,
      {
        method: "DELETE",
      }
    );

    // console.log("Delete", id);
    setTasks(tasks.filter(task => task.id !== id));
  };

  // Toggle reminder
  const toggleReminder = async (id) => {

    const taskToToggle= await fetchTask(id);
    const updTask= {...taskToToggle, reminder: !taskToToggle.reminder};

    const res = await fetch(
      `http://localhost:5000/tasks/${id}`,
      {
        method: "PUT",
        headers: {
          "Content-type": "application/json",
        },
        body: JSON.stringify(updTask),
      }
    );

    const data = await res.json();

    // console.log("Toggle Reminder", id);
    setTasks(tasks.map(task => {
      if (task.id === id) {
        return {
          ...task,
          reminder: data.reminder
        };
      }
      return task;
    }));
  };

  return (
    <div className="container">
      <Header
        title="Task Tracker"
        onAdd= {() => setshowAddTask(!showAddTask)}
        showAddTask={showAddTask}
      />
      {/* <Header title = "Hello" /> */}
      {/* <Header title = {1} /> */}
      {/* <ErrorBoundary fallback={<h2>Header failed to load</h2>}>
        <Header />
      </ErrorBoundary> */}
      {/* <h1>Hello From React</h1> */}
      {/* <h2>Hello {name} {x ? "How are you!" : "Go to hell"}</h2> */}
      {showAddTask && <AddTask onAdd={addTask} />}
      {tasks.length > 0 ?
      (<Tasks
        tasks={tasks}
        onDelete={deleteTask}
        onToggle= {toggleReminder}
      />) :
      "No Tasks To Show"}
    </div>
    // <>
    //   <h1>Hello From React</h1>
    //   <h2>Hello</h2>
    // </>
  );
}

export default App;
